// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	jwt "UsersService/pkg/jwt"

	mock "github.com/stretchr/testify/mock"
)

// JWTClient is an autogenerated mock type for the JWTClient type
type JWTClient struct {
	mock.Mock
}

// NewJWT provides a mock function with given fields: user
func (_m *JWTClient) NewJWT(user jwt.CreateTokenParams) (string, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for NewJWT")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(jwt.CreateTokenParams) (string, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(jwt.CreateTokenParams) string); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(jwt.CreateTokenParams) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ValidateJWT provides a mock function with given fields: token
func (_m *JWTClient) ValidateJWT(token string) error {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ValidateJWT")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewJWTClient creates a new instance of JWTClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJWTClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *JWTClient {
	mock := &JWTClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
